# Pulsar settings
pulsar:
  tenant: infinitic
  namespace: dev
  # brokerServiceUrl: pulsar+ssl://dev.infinitic.snio.cloud:6651
  # webServiceUrl: https://dev.infinitic.snio.cloud
  # authentication:
    # issuerUrl: https://auth.streamnative.cloud
    # privateKey: file:///Users/gilles/.sn/infinitic-admin.json
    # audience: urn:sn:pulsar:infinitic:test

# Storage settings
storage:
  #inMemory:
  #mysql:
  #  host: localhost
  #  port: 3306
  #  user: root
  #  password:
  #  database: infinitic
  redis:
    # host: localhost
    # port: 6379
    # user:
    # password:
    # database: 0

# Dashboard Settings
port: 9080
