tasks:
  - name: CarRental
    class: example.booking.tasks.carRental.CarRentalServiceFake
    concurrency: 10
  - name: FlightBooking
    class: example.booking.tasks.flight.FlightBookingServiceFake
    concurrency: 10
  - name: HotelBooking
    class: example.booking.tasks.hotel.HotelBookingServiceFake
    concurrency: 10

workflows:
  - name: BookingWorkflow
    class: example.booking.workflows.BookingWorkflowImpl
    concurrency: 10
