# Common settings
pulsar:
  tenant: infinitic
  namespace: dev
#  brokerServiceUrl:
#  webServiceUrl:
#  authentication:
#    issuerUrl:
#    privateKey:
#    audience:

# Workers settings
stateStorage: redis

#mysql:
#  host: localhost
#  port: 3306
#  user: root
#  password:
#  database: infinitic


#redis:
#  host: localhost
#  port: 6379
#  user:
#  password:
#  database: 0

# Dashboard Settings
port: 9080
